"""
Australia Chair Daily Brief: source list generator
CSIS Australia Chair

Writes SOURCES.md from collect.py and newsletters.py.

The feed set only ever existed as four dicts in collect.py, which meant the
answer to "what does this brief actually read?" was "open the collector and
count". That is a fair question from anyone deciding whether to trust the
product, and it should not require reading Python.

Generated rather than hand-written, because a hand-written list is wrong the
first time somebody adds a feed and nobody notices for a month. Re-run after
any change to the feed dicts:

    python list_sources.py

smoke_test.py checks the committed file is current, so a stale one fails the
suite rather than quietly misleading a reader.
"""
import io
from urllib.parse import urlparse, parse_qs, unquote

import collect
import newsletters

OUT = "SOURCES.md"


def _url_of(value) -> str:
    """Tiers 2 and 3 carry (url, rank); tiers 1 and 4 carry a bare url."""
    return value[0] if isinstance(value, tuple) else value


def _route(url: str) -> tuple[str, str]:
    """How a feed is fetched, and what it asks for."""
    if "news.google.com" in url:
        query = parse_qs(urlparse(url).query).get("q", [""])[0]
        edition = "US" if "gl=US" in url else "AU"
        return f"Google News ({edition})", unquote(query).replace("|", "\\|")
    return "direct RSS", urlparse(url).netloc


def _rows(feeds: dict) -> list[str]:
    rows = []
    for name, value in feeds.items():
        how, detail = _route(_url_of(value))
        region = collect._SOURCE_REGION.get(name, "AU")
        star = " **\\***" if name in collect._PRESTIGE_FEEDS else ""
        rows.append(f"| {name}{star} | {region} | {how} | `{detail[:78]}` |")
    return rows


def build() -> str:
    tiers = [
        ("Tier 1: news", collect.TIER1_FEEDS,
         "The daily corpus. Everything the brief reports comes from here or "
         "from tier 4."),
        ("Tier 2: analysis and commentary", collect.TIER2_FEEDS,
         "Think tanks and columnists. Lowy Interpreter, ASPI Strategist and "
         "Devpolicy carry a mandatory-inclusion rule of their own: a same-day "
         "piece always appears, even when the section is full."),
        ("Tier 3: academic journals", collect.TIER3_FEEDS,
         "Slow, and included for the weeks when a journal lands something the "
         "press has not caught up with."),
        ("Tier 4: primary documents", collect.TIER4_FEEDS,
         "Communiques, joint statements, testimony. The brief prefers these to "
         "any reporting of them."),
    ]
    total = sum(len(f) for _, f, _ in tiers)

    lines = [
        "# Sources",
        "",
        "**Generated by `python list_sources.py`. Do not edit by hand.**",
        "",
        f"{total} feeds across four tiers, plus subscriber newsletters over IMAP.",
        "",
        "Two things to read off the table:",
        "",
        "- **Region** decides which regional count a story lands in, and the "
        "Pacific count is what protects Pacific coverage. A Pacific outlet "
        "missing from `_SOURCE_REGION` files as Australian and the Pacific "
        "count reads low while input is fine.",
        "- **\\*** marks a prestige feed. A qualifying story from one of these "
        "must appear in the brief; the item is flagged in the data the model "
        "reads, and the validator warns by headline if one is dropped.",
        "",
        "Google News routing is not a fallback, it is the rule for any "
        "publisher that paywalls, blocks bots, or returns 403. A feed that "
        "dies gets rerouted, never deleted.",
        "",
    ]

    for title, feeds, note in tiers:
        lines += [
            f"## {title}",
            "",
            f"{len(feeds)} feeds. {note}",
            "",
            "| Source | Region | Fetched via | Feed or query |",
            "| --- | --- | --- | --- |",
            *_rows(feeds),
            "",
        ]

    lines += [
        "## Newsletters over IMAP",
        "",
        "Controlled by the repository variable `NEWSLETTERS`, off unless it is "
        "`1`. This file is generated from the code and cannot see a repository "
        "variable, so check the Actions Variables tab for the live setting. "
        "Reads the `GMAIL_USER` inbox first, then All Mail, since a newsletter "
        "is exactly the mail a Gmail filter is set up to label and skip the "
        "inbox. For a newsletter you subscribe to there is no wall to defeat: "
        "the publisher mailed you the issue with the editing already done.",
        "",
        "Matched on sender and subject together, so whichever the inbox "
        "receives is picked up. An unsubscribed fingerprint simply never "
        "matches, which is why the list can be longer than what you take.",
        "",
        "| Subject contains | Reported as |",
        "| --- | --- |",
        *[f"| `{k}` | {d} |" for k, d in newsletters._NEWSLETTERS],
        "",
        "Publisher fingerprints, matched on the sender and composed into the "
        "label as `Publisher (Newsletter)`:",
        "",
        "| Sender contains | Publisher |",
        "| --- | --- |",
        *[f"| `{k}` | {d} |" for k, d in newsletters._PUBLISHERS],
        "",
        "## Market data",
        "",
        "`markets.py`, Yahoo Finance with a Stooq fallback, rendered only for "
        "what actually resolved:",
        "",
        "| Indicator | Yahoo | Stooq |",
        "| --- | --- | --- |",
        *[f"| {label} | `{y}` | {f'`{s}`' if s else 'none'} |"
          for _, label, y, s, _ in markets_indicators()],
        "",
        "Iron ore is deliberately absent. Yahoo's `TIO=F` stopped updating and "
        "returns quotes over 1,800 days old, which `markets.py` correctly "
        "refuses. See SETUP before restoring it.",
        "",
    ]
    return "\n".join(lines) + "\n"


def markets_indicators():
    import markets
    return markets.INDICATORS


if __name__ == "__main__":
    text = build()
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    n = text.count("\n| ") - text.count("| --- |")
    print(f"  -> {OUT} ({len(text):,} bytes)")
